databases:
  - name: worship-tree-db
    plan: free
    databaseName: worship_tree
    user: worship_tree

services:
  - type: web
    name: worship-tree
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn worship_tree.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: worship-tree-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
